{% set version = "2.0.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-pgirmess
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pgirmess_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pgirmess/pgirmess_{{ version }}.tar.gz
  sha256: 765271cf9a0857e094cb4b4c075b2d0073c7e3ee812ebf6bcbbd87c12e633ab0

build:
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-boot >=1.3_4
    - r-sf >=1.0_4
    - r-sp >=0.9_97
    - r-spdep >=1.1_7
  run:
    - r-base
    - r-boot >=1.3_4
    - r-sf >=1.0_4
    - r-sp >=0.9_97
    - r-spdep >=1.1_7

test:
  commands:
    - $R -e "library('pgirmess')"           # [not win]
    - "\"%R%\" -e \"library('pgirmess')\""  # [win]

about:
  home: http://perso.orange.fr/giraudoux
  license: GPL-2.0-or-later
  summary: Set of tools for reading, writing and transforming spatial and seasonal data in ecology, model selection and specific statistical tests. It includes functions to discretize polylines into regular point intervals, link observations to those points, compute geographical coordinates at regular intervals between waypoints,
    read subsets of big rasters, compute zonal statistics or table of categories within polygons or circular buffers from raster. The package also provides miscellaneous functions for model selection, spatial statistics, geometries, writing data.frame with Chinese characters, and some other functions for field ecologists.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
