{% set version = "1.7.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pgirmess
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pgirmess_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pgirmess/pgirmess_{{ version }}.tar.gz
  sha256: 3ec286b7e1c9763a66ff26b360d6d9a19f04b88715aeafbe2f4ad92514db05ce

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-boot >=1.3_4
    - r-maptools >=0.8_36
    - r-rgdal >=0.7_8
    - r-rgeos >=0.3_8
    - r-sp >=0.9_97
    - r-spdep >=0.5_43
    - r-splancs >=2.01_31
  run:
    - r-base
    - r-boot >=1.3_4
    - r-maptools >=0.8_36
    - r-rgdal >=0.7_8
    - r-rgeos >=0.3_8
    - r-sp >=0.9_97
    - r-spdep >=0.5_43
    - r-splancs >=2.01_31

test:
  commands:
    - $R -e "library('pgirmess')"           # [not win]
    - "\"%R%\" -e \"library('pgirmess')\""  # [win]

about:
  home: http://perso.orange.fr/giraudoux
  license: GPL (>= 2)
  summary: Set of tools for reading, writing and transforming spatial and seasonal data in ecology, model selection and specific statistical tests. It includes functions to discretize polylines into regular point intervals, link observations to those points, compute geographical coordinates at regular intervals between waypoints,
    read subsets of big rasters, compute zonal statistics or table of categories within polygons or circular buffers from raster. The package also provides miscellaneous functions for model selection, spatial statistics, geometries, writing data.frame with Chinese characters, and some other functions for field ecologists.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: pgirmess
# Version: 1.6.9
# Date: 2018-03-11
# Title: Spatial Analysis and Data Mining for Field Ecologists
# Authors@R: c(person("Patrick", "Giraudoux", role = c("aut", "cre"), email = "patrick.giraudoux@univ-fcomte.fr"), person("Jean-Philippe", "Antonietti", role = c("ctb"), email = "Jean-Philippe.Antonietti@unil.ch"), person("Colin", "Beale", role = c("ctb"), email = "c.beale@macaulay.ac.uk"),person("David", "Pleydell", role = c("ctb"), email = "david.pleydell@inra.fr"), person("Mike", "Treglia", role = c("ctb"), email = "mike-treglia@utulsa.edu"))
# Author: Patrick Giraudoux [aut, cre], Jean-Philippe Antonietti [ctb], Colin Beale [ctb], David Pleydell [ctb], Mike Treglia [ctb]
# Maintainer: Patrick Giraudoux <patrick.giraudoux@univ-fcomte.fr>
# Description: Set of tools for reading, writing and transforming spatial and seasonal data in ecology, model selection and specific statistical tests. It includes functions to discretize polylines into regular point intervals, link observations to those points, compute geographical coordinates at regular intervals between waypoints, read subsets of big rasters, compute zonal statistics or table of categories within polygons or circular buffers from raster. The package also provides miscellaneous functions for model selection, spatial statistics, geometries, writing data.frame with Chinese characters, and some other functions for field ecologists.
# Imports: boot (>= 1.3-4), maptools (>= 0.8-36), rgdal (>= 0.7-8), rgeos (>= 0.3-8), sp (>= 0.9-97), spdep (>= 0.5-43), splancs (>= 2.01-31)
# Suggests: MASS (>= 7.3-1), nlme (>= 3.1-120)
# License: GPL (>= 2)
# URL: http://perso.orange.fr/giraudoux
# NeedsCompilation: no
# Packaged: 2018-03-12 02:59:59 UTC; pgiraudo2
# Repository: CRAN
# Date/Publication: 2018-03-12 14:56:20 UTC
