travis:
  secure:
    BINSTAR_TOKEN: pgZh9lyQdDVoLKvvsQIMac6hqqxZxrb1vqnHcPqmldioFUtMqYrnfKoF6hE/Nq+GNwsqb7FV8nii9Gwz/7/jgwdgJj38G7TTC2PFaYGDCZMhc7892tx+luXW4oHHv/v2VydPMfkszyandc3gM0+Hp+QB160DVckHBWlHTOLVWNRwGKKSprWqlRqd0TBLarUwAEkvY1xU6NzpBlkhAJgHW0bOlycHKjHWBs91i2tHx9AndE8IHJ7Nw7k1UVSCiuRi/00UHs0GanrVpoQoBEyeCSM2AyMiCGHgJw44J9BLeI3kzL2WDlI2+FBqwiE1dm3KwUEsiWyv8YEXQNo1WLvOuwfKaHICqR2tjeBNsXtOWwMAX67v7ad0O8xzrl04461Cgjk4898/LFEt9kNwxupW7/rhj4u+MB9gWOzyNAShx9pHrjgS3mcchb8VkIyNBCJP8Nx7zcwOk8BppUEST1SDpE5/vHw0Fl3VyRH/jKcIg/KvUsSY9rDJjtZmZ1iRZPKqdPBmYH8CS5xgy6ks1I4AcG1krXVV8JVuLrXWVQFlWEyAKDbC6+AhgKSW+SnY9uvRWPWB9OEDetiEwmT8svD4uNfDSLxN/iSbxBZdqKinbP3R2RCPbrz3f2JSmZzSsdsf1ipO4EaRv09zVlfAnf73hvqRfaeVAH6TtUe931x43T0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
