appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: eRcIq9VIRXbZWHEg1/Eo+g9EcHToolX/eXucXJzANCdYjIl/APn2yAH84bz3qA+zphZ40DeO/hmFOMEScXGSs+e7xSLWjLE9Sf7XkAV3SdgXVXF3JNZZxiMz7T9S5bcuLpH9OwUzx3vqYyjVO3SCe5djt7UJpx+vFLqNMIdNSlMN4UBPT4gujpZogXkPCCmm29Z1y71XMd/ZPGCx+uOcmZSOP2EuswpYW/y4v3ply83bx6RqprrXB8z3tUJjxhc3d9DRIUaK2YfIIEm8D5w2XFVQwUpfp72cZBPS1e5U2g7HgN40rCo77RWiCo19/dtNGCllZgr8JvzdWjZBczh0h2dWSvLD5J3DP+OCDYt8hE0bvOvgVQ+y3Yg5wWm9ZuzyMjHFwXTrROdfJbV5t0/0C+PgaGyQTaTwiqu7r1drpRUMjAlR3OeEu1FuN3p85/vG1MxveE90/zLQiTJJ4O/MH3rUjw3AVuhf4WBp/raguCGJff3/KcGgzMytIK3tos+jcY/eijxNRvYPMD2cjOMpHbFw4hOF83IbDBrzQWOJn9zPt8PIz8IEnlSnTE+PIaxXajtwyy0YqSLyhcRS+TqUpEQcUi2tqCDP3gyL8MQgM9L6iliq/VulIhG0TTaRNxiVGkfSK5LcZTMEE1EPhskqUbIKdYP7f2ggn9o0ptYYyF8=}
bot:
  automerge: true
