travis:
  secure:
    BINSTAR_TOKEN: KWlmEwX9S1/7wFOyShCUt9hD2Czp6XXORHkDoGCGrKtttustIkFZ2jG5ZF40Vfg97/KvBjKrnRrgbbBwOf/w2R9o4Ow3aSgqegr7avLq3Y6jX8gTSgCTveIKh7wW8KWX4jLCXQ6pfFXKcySsmJDz3VQCebzO85LifbQHfhIEkF2OT85xUm5UOaWBuK5Mu3DY0rA2U34vhDBMuxIgmZ1dPMDBBtpCyOZ+m/HaHlEsLSLqWoucOuXhBNzTpBWOtQaK3xDEPqzddnMQGCO0apkbhTHs9ghKoU3VQNinAnl9EH/vZpuwkZwwIQVuMFcLNyJt0LyPoRPB5y90hkSIwTfpbnr3n4BOJtg5sErTIVXOtPAjPVXIQRg0dJd/40e1i90Tse60gj9xLmFvA5s08yBeOMe0XvHQqUaf/2m8GHU/o8p49nFEI2MKjljWpwEkLdgikBxzMiXuV83oRPcNFaMHw2LKsTBFCTf2HZrKqRFXBqyWDJ8Cw1agFBmYxq2zTDHdayKoHU6JL5LQLUzwTQZs092Od5FCbt/5eV9CStWFaJZPienvMh+H9vmwnHL6Y+qyYhmYrYuyiVG5wZtj2Dku9xqyWBBvGLSwVJ7gXIAriCbslAYV2JG+LdXB4Fh6EDxWLJ39YodcC0jGZpVOch6ZBs3gpIb6AdT6nGhTRr3vwMI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
